# Generated by Django 5.2.7 on 2025-11-06 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('clave', models.CharField(max_length=10)),
                ('correo', models.CharField(max_length=30)),
                ('foto_perfil', models.ImageField(default='usuarios/imagen.png', upload_to='usuarios/')),
            ],
            options={
                'managed': True,
            },
        ),
    ]
